use Mix.Config

config :njuus, Njuus.Core.Categories,
  icons: %{
    "uudised" => "icons/news.svg",
    "sündmused" => "icons/event.svg",
    "poliitka" => "icons/politics.svg",
    "sport" => "icons/Sports.svg",
    "tehnika" => "icons/Technology.svg",
    "majandus" => "icons/economy.svg",
    "kultuur" => "icons/theatre.svg",
    "maailm" => "icons/Globe.svg",
    "elu" => "icons/nature.svg",
    "naistekas" => "icons/Lips.svg",
    "krüptoraha" => "icons/Bitcoin.svg",
    "112" => "icons/emergency.svg",
    "saated" => "icons/TV.svg",
    "60+" => "icons/Plus.svg",
    "muu" => "icons/other.svg"
  },
  pairs: %{
    "uudised" => [
      "Eesti",
      "Uudised",
      "Teateid elust",
      "Kuum",
      "Liiklus",
      "10 Minutit",
      "Eesti Ekspress 30",
      "Tarbija",
      "Arvamus",
      "Arvamused",
      "Ühiskond",
      "Keskkond",
      "eurovalimised",
      "R2 Portaal",
      "Inimesed",
      "Varia",
      "Videod",
      "Õhtu!",
      "Video",
      "Avaleht",
      "Juhtkiri"
    ],
    "sündmused" => ["Sündmused", "ESTO 2019", "Kes ja kus"],
    "poliitka" => ["Tööintervjuu", "Poliitika"],
    "sport" => [
      "Jalgpall",
      "Tennis",
      "Jalgrattasport",
      "Tervisesport",
      "Vormel-1",
      "Premium liiga",
      "Maadlus",
      "Jäähoki",
      "Jäähoki MM",
      "Motosport",
      "Võrkpall",
      "Korvpall",
      "Võrkpalli Eesti koondis",
      "ETV spordisaade",
      "Olümpialiikumine",
      "Invasport",
      "Judo",
      "Vehklemine",
      "Võimlemine",
      "Jääkeegel",
      "sport",
      "Veemoto",
      "Kergejõustik",
      "Rallikross",
      "Autoralli",
      "Spordipoliitika",
      "Sport",
      "F1",
      "Purjetamine",
      "Ratsutamine",
      "Jalgratas",
      "WRC",
      "Võitlussport",
      "Kulturism ja fitness",
      "Spordireporter",
      "Mäesuusatamine",
      "Talisport",
      "Koolisõit"
    ],
    "tehnika" => ["Teaduselu", "Tehnika", "E-sport", "Heureka"],
    "majandus" => [
      "Majandus",
      "Kinnisvara",
      "Börsiuudised",
      "Majandustulemused",
      "Investor Toomas",
      "Kaupleja Alex",
      "Sisuturundus",
      "Erilehed"
    ],
    "kultuur" => [
      "Kultuur",
      "Areen",
      "Eesti Muusika Päevad",
      "Muusika",
      "Kirjandus",
      "kultuur",
      "Laulupidu 2019",
      "Film",
      "Kunst",
      "Galeriid",
      "Muuseumid",
      "Eurovisioon",
      "Tele/raadio",
      "Teater",
      "Ajalugu",
      "Ajaviide",
      "Kinoportaal",
      "Apollo Kino sündmused",
      "Raamatuportaal",
      "TV",
      "Tele",
      "Filmid",
      "Katkendid",
      "Kassahitid"
    ],
    "maailm" => ["Maailm", "Välismaa"],
    "elu" => [
      "Lapsed",
      "Sisustus ja disain",
      "Koolilaps",
      "Elu",
      "Kaameraga maal",
      "Juubelipidu",
      "Aed",
      "Leili metsalood",
      "Kodu",
      "Seadus",
      "Loodus",
      "Tervis",
      "Maa Elu",
      "Ehitus ja viimistlus",
      "Aed",
      "Loomariik",
      "Lemmik",
      "Koerad",
      "Teeme ise",
      "Ema ja laps",
      "Põllumajandus",
      "Päevakäpp"
    ],
    "naistekas" => [
      "Ilu",
      "Ilu & mood",
      "Sõbranna",
      "Kirev elu",
      "Elu24",
      "Reis & elustiil",
      "Kodustiil",
      "Pere",
      "Suhted & seks",
      "Maitsemeel",
      "Seltsielu",
      "Persoon",
      "Fläsh!",
      "Sodiaagisaladused"
    ],
    "krüptoraha" => [],
    "112" => ["Krimi", "112"],
    "tallinn" => ["Tallinn"],
    "virumaa" => ["Virumaa Teataja"],
    "tartu" => ["Tartu Postimees"],
    "pärnu" => ["Pärnu Postimees"],
    "lõuna-eesti" => ["Lõuna-Eesti Postimees"],
    "valga" => ["Valga"],
    "saared" => ["Saarte Hääl"],
    "saated" => [
      "Raadiouudised",
      "Teleuudised",
      "Järelvaatamine",
      "Noortesaade NOVA",
      "Radar",
      "Otse Postimehest",
      "Reporter"
    ],
    "60+" => ["60+"],
    "muu" => ["ilm", "Meedia", "Leht"]
  }
