use Mix.Config

config :njuus, Njuus.Core.Categories,
  icons: %{
    "uudised" => "icons/news.svg",
    "sündmused" => "icons/event.svg",
    "poliitka" => "icons/politics.svg",
    "sport" => "icons/Sports.svg",
    "tehnika" => "icons/Technology.svg",
    "majandus" => "icons/economy.svg",
    "kultuur" => "icons/theatre.svg",
    "maailm" => "icons/Globe.svg",
    "elu" => "icons/nature.svg",
    "naistekas" => "icons/Lips.svg",
    "krüptoraha" => "icons/Bitcoin.svg",
    "112" => "icons/emergency.svg",
    "saated" => "icons/TV.svg",
    "60+" => "icons/Plus.svg",
    "muu" => "icons/other.svg"
  },
  pairs_ignore: ["Postimees", "Tasuline", "Lisa", "Töökuulutused"],
  pairs: %{
    "uudised" => [
      "Eesti",
      "Uudised",
      "uudised",
      "Teateid elust",
      "Kuum",
      "Liiklus",
      "10 Minutit",
      "Eesti Ekspress 30",
      "Tarbija",
      "Arvamus",
      "Arvamused",
      "Arhiiv",
      "Ühiskond",
      "Keskkond",
      "eurovalimised",
      "R2 Portaal",
      "Inimesed",
      "Varia",
      "Videod",
      "Õhtu!",
      "Tänane leht",
      "Video",
      "Avaleht",
      "Juhtkiri"
    ],
    "sündmused" => ["Sündmused", "ESTO 2019", "Kes ja kus", "Laulupidu", "Tantsupidu"],
    "poliitka" => ["Tööintervjuu", "Poliitika", "Kranaat"],
    "sport" => [
      "Jalgpall",
      "Tennis",
      "Jalgrattasport",
      "Tervisesport",
      "Vormel-1",
      "Premium liiga",
      "Maadlus",
      "Jäähoki",
      "Jäähoki MM",
      "Motosport",
      "Võrkpall",
      "Korvpall",
      "Võrkpalli Eesti koondis",
      "ETV spordisaade",
      "Olümpialiikumine",
      "Invasport",
      "Judo",
      "Kergejõustiku MM",
      "Snuuker ja piljard",
      "Vehklemine",
      "Võimlemine",
      "Jääkeegel",
      "sport",
      "Veemoto",
      "Kergejõustik",
      "Rallikross",
      "Autoralli",
      "Spordipoliitika",
      "Sport",
      "F1",
      "Jalgpalli MM",
      "Väravad",
      "Käsipall",
      "Laskesuusatamine",
      "ETV spordi lühiuudised",
      "Ujumine",
      "Poks",
      "Aerutamine",
      "Golf",
      "Ratsasport",
      "Purjetamine",
      "Ratsutamine",
      "Jalgratas",
      "WRC",
      "Võitlussport",
      "Kulturism ja fitness",
      "Spordireporter",
      "Mäesuusatamine",
      "Talisport",
      "Koolisõit"
    ],
    "tehnika" => ["Teaduselu", "Tehnika", "E-sport", "Heureka", "Digi"],
    "majandus" => [
      "Majandus",
      "Kinnisvara",
      "Börsiuudised",
      "Majandustulemused",
      "Investor Toomas",
      "Juhtimine",
      "Metsandus",
      "Kaupleja Alex",
      "Sisuturundus",
      "Erilehed"
    ],
    "kultuur" => [
      "Kultuur",
      "Areen",
      "Eesti Muusika Päevad",
      "Muusika",
      "Kirjandus",
      "kultuur",
      "Laulupidu 2019",
      "Elmar LIVE",
      "Elmar.ee",
      "Film",
      "Uued plaadid",
      "Kunst",
      "Galeriid",
      "Muuseumid",
      "Eurovisioon",
      "Tele/raadio",
      "Teater",
      "Ajalugu",
      "Ajaviide",
      "Kinoportaal",
      "Apollo Kino sündmused",
      "Tähtede lava",
      "Raamatuportaal",
      "TV",
      "Tele",
      "Filmid",
      "Katkendid",
      "Kassahitid"
    ],
    "maailm" => ["Maailm", "Välismaa"],
    "elu" => [
      "Lapsed",
      "Sisustus ja disain",
      "Koolilaps",
      "Elu",
      "Kaameraga maal",
      "Juubelipidu",
      "Aed",
      "Leili metsalood",
      "Haridus",
      "Aasta kool",
      "Viipekeelsed",
      "Universum",
      "Vali kool",
      "Kuuuurija",
      "Kodu",
      "Seadus",
      "Loodus",
      "Tervis",
      "Osoon",
      "Maa Elu",
      "Ehitus ja viimistlus",
      "Aed",
      "Loomariik",
      "Lemmik",
      "Koerad",
      "Teeme ise",
      "Ema ja laps",
      "Põllumajandus",
      "Päevakäpp"
    ],
    "naistekas" => [
      "Ilu",
      "Ilu & mood",
      "Sõbranna",
      "Kirev elu",
      "Elu24",
      "Reis & elustiil",
      "Kodustiil",
      "Reisile",
      "Pere",
      "Suhted & seks",
      "Reis",
      "Maitsemeel",
      "Seltsielu",
      "Persoon",
      "Fläsh!",
      "Sodiaagisaladused"
    ],
    "krüptoraha" => [],
    "112" => ["Krimi", "112"],
    "tallinn" => ["Tallinn", "Tallinna Vanalinna Päevad"],
    "virumaa" => ["Virumaa Teataja"],
    "tartu" => ["Tartu Postimees"],
    "pärnu" => ["Pärnu Postimees"],
    "lõuna-eesti" => ["Lõuna-Eesti Postimees"],
    "järva" => ["Järva Teataja"],
    "valga" => ["Valga"],
    "saared" => ["Saarte Hääl"],
    "saated" => [
      "Raadiouudised",
      "Teleuudised",
      "Järelvaatamine",
      "Noortesaade NOVA",
      "Radar",
      "Otse Postimehest",
      "Saated",
      "ETV uudised",
      "Reporter"
    ],
    "60+" => ["60+"],
    "muu" => ["ilm", "Meedia", "Leht", "Džiugas"]
  }
